import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import { Toaster } from 'react-hot-toast'
import './globals.css'
import MiniCart from '@/components/MiniCart'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position='top-right' reverseOrder={false} />

        {/* Global Navigation */}
        <nav className='flex justify-between items-center p-4 bg-gray-100 shadow-md'>
          <div className='flex gap-6'>
            <Link href='/' className='hover:underline font-medium'>
              Home
            </Link>
            <Link href='/products' className='hover:underline font-medium'>
              Products
            </Link>
            <Link href='/cart' className='hover:underline font-medium'>
              Cart
            </Link>
          </div>
          <MiniCart />
        </nav>

        {/* Page Content */}
        <main className='p-4'>{children}</main>
      </body>
    </html>
  )
}
